#+TITLE: Heterogeneous firing response of mice layer V pyramidal neurons in the /fluctuation-driven/ regime
#+AUTHOR: Y. Zerlaut^{1,2}, B. Telenczuk^{1,2},  C. Deleuze^1, T. Bal^1, G. Ouanounou^{1}* \& A. Destexhe^{1,2}*
#+INCLUDE: my_template.org 

* Abstract

\bfseries 

  Characterizing the input-output properties of neocortical neurons is
  of crucial importance to understand the properties emerging at the
  network level. In the regime of low-rate irregular firing (such as
  in the /awake/ state) determining those properties for neocortical
  cells remains, however, both experimentally and theoretically
  challenging.  Here, we identified three somatic variables that
  describe the dynamical state at the soma in the /fluctuation-driven/
  regime: the mean, standard deviation and speed of the membrane
  potential fluctuations. We characterized the firing rate response of
  individual layer V pyramidal cells in this three-dimensional space
  by means of /dynamic-clamp/ and perforated patch recordings in the
  visual cortex of juvenile mice /in vitro/. We found that single
  neurons strongly differ in terms of their excitability and
  sensitivities to the variations in the three parameters of the
  fluctuations. We show with theoretical modeling that heterogeneous
  levels of biophysical properties such as sodium inactivation,
  sharpness of sodium activation and spike frequency adaptation might
  be the main contributors to the observed diversity of firing
  responses. Because the firing rate response will determine
  population rate dynamics during asynchronous neocortical activity,
  our results show that cortical populations are functionally strongly
  inhomogeneous in young mice visual cortex, which should have
  important consequences on cortical computation at early stages of
  sensory processing.

\normalfont


* Significance statement

\bfseries 

Heterogeneity is an ubiquitous property of biological systems, but
characterizing its extent and functional impact represents a challenge
for experimentalists. Here we developed a method to characterize the
response of single neocortical layer V pyramidal cells of young mice
visual cortex in an activity domain imitating normal awake state. We
found that individual neurons greatly differ not only in their
excitability but also in their ability to trigger spikes as a function
of the characteristics of the membrane potential fluctuations. By
highlighting and quantifying this diversity, our study contributes to
the understanding of how biological heterogeneity impacts neocortical
computations.

\normalfont


* Introduction

The neocortex of awake animals displays an activated state in which
cortical activity manifests highly complex, seemingly noisy
behavior. At the level of single neurons the activity is characterized
by strong subthreshold fluctuations and irregular firing at low rate:
this constitutes the fluctuation-driven regime, which is believed to
be central to cortical computations [[citep:Destexhe2006]]. Since sensory
processing of natural stimuli also evoke sparse response at low
population rates, see for example [[citet:Baudot2013]] in cat V1,
understanding the dynamical and computational properties of this
regime at the cellular and network level is a key challenge in systems
neuroscience.

On the other hand sparse responses at low population rates constitute
a difficulty for experimentalists /in vivo/ as
responses are of low amplitude and render experimental
characterization challenging. To a lesser extent, this is also true
/in vitro/, characterizing the spiking response of single neurons at
low rate requires long recording times and stable properties. In the
present paper, we propose a characterization of the low rate response
of single neurons that was made possible by the combination of the
stability offered by the perforated patch technique technique and a
simple fitting procedure for the spiking response.

We investigate single neuron responses with respect to three somatic
variables: the mean, standard deviation and speed of the membrane
potential fluctuations at the soma. In comparison with previous work
[[citep:LaCamera2008]], our approach allows to investigate the response to
fast membrane potential fluctuations present in the /high conductance/
state of cortical networks [[citep:Destexhe2003]]. This characterization
focuses on how these fluctuations are translated into output spikes on top
of subthreshold integration effects [[citep:Kuhn2004]]. In addition, we
also investigated the putative biophysical origin of the measured
responses in established theoretical models of single neurons.


* Results 
<<sec:results>>
\normalsize

The paper is organized as follows: we start by we defining the
fluctuation-driven regime at the soma and designing a method to
reproduce this somatic dynamical state under dynamic-clamp
experiments. We also derive a flexible template for the firing rate
response, whose accuracy is demonstrated on various theoretical
models. Then, we investigate the firing response of layer V pyramidal
cells in mice juvenile cortex and we analyze the individual features
of single neuron responses. Finally, we explore the putative
biophysical origin of the observed response in theoretical models of
neocortical neurons.

** A three-dimensional description of the dynamical state at the soma in the fluctuation-driven regime
<<sec:3D-space>>

# #+ATTR_LATEX: :float c :width .6\linewidth
#+ATTR_LATEX: :float c
#+CAPTION: *Investigating somatic computation in the fluctuation-driven regime* *(A)* Schematic illustration on a layer V pyramidal cell in cat V1 [[citep:Contreras1997]] together with theoretical distribution of inhibitiory (red) and excitatory (green) synaptic inputs. Synaptic and dendritic integration of pre-synaptic spike trains (two sample spike trains in upper right) produce membrane potential fluctuations at the soma as recorded intracellularly in current-clamp. *(B)* A sample trace of membrane potential integrating inputs from all inhibitory and excitatory synapses (black trace). We characterize those fluctuations by a mean \mu_V (dashed horizontal line), a standard deviation \sigma_V of sub-threshold oscillations (gray background) and global autocorrelation time \tau_V (determined from the normalized autocorrelation function in the inset, see Methods[[sec:autocorrel-def]]). The properties of those fluctuations determine the spiking probability of the neuron (three spikes visible in the membrane-potential trace).
#+NAME: fig:3D-motiv
[[file:./figures/vm_traces.pdf]]


Determining the cellular input-output functions is complex because
input of neocortical neurons are mostly in dendrites and output spikes
are generated in initial segments of an axon as reviewed in
[[citet:Stuart2015]] and [[citet:Debanne2011]] 
input will therefore crucially shape their input-output
relationship. Various parameters of presynaptic activity can
arbitrarily control the properties of the membrane potential
fluctuations at the soma. Those properties can be quantified by
identifying three somatic variables that provide a reduced description
of the dynamical state at the soma in the /fluctuation-driven/ regime:
the mean \mu_V, the standard deviation \sigma_V of the membrane
potential fluctuations and their typical autocorrelation time $\tau_V$
(see Methods[[sec:autocorrel-def]]). For example, the
excitatory/inhibitory balance controls the mean depolarization at the
soma \mu_V, the mean synaptic bombardment impacts the standard
deviation \sigma_V and the speed of the membrane potential
fluctuations \tau_V. Other effects such as synchrony in the
presynaptic spike trains or ratio between distally and proximally
targeting synaptic activity also affect the statistical properties of
the fluctuations. The effects of synaptic input and its dendritic
integration on somatic variables can be investigated theoretically
using cable theory [[citep:Tuckwell2002]] and will be the focus of a future
communication.

Because the spike initiation site lies electrotonically close to the
soma [[citep:Debanne2011]], we assume that those three purely somatic
variables will define the firing rate uniquely. In this study we
investigate the firing response in terms of those somatic variables
(illustrated in Figure [[fig:3D-motiv]]).

We therefore designed a stimulation protocol to reproduce awake-like
dynamical state at the soma and investigate the firing response in
this three dimensional space. We evaluate the parameters of stochastic
current and static conductance that would result in a particular
configuration of the V_m fluctuations (\mu_V, \sigma_V and \tau_V) for
passive membrane using a single-compartment approximation
[[citep:Kuhn2004]].  This procedure allows to focus on how active currents
convert fluctuations into spikes. Another advantage of this approach
is that it naturally rescales the input with respect to the individual
cellular properties (R_m, C_m and E_L) and therefore allows a
cell-by-cell comparison. In addition, we investigated domains of the
dimensionless variable \tau_V^N = \tau_V / \tau_m^0 instead of
absolute values for membrane time constant \tau_V to account for
scaling of the synaptic inputs with membrane area (Equation [[eq:TvN]] in
Methods[[sec:stimulation-design]]).



** Template for the firing rate response of single neurons 
<<sec:building-template>>

 A key challenge for the /in vitro/ characterization of input-output
 relationship is to extract a reliable quantitative estimation of its
 functional form from a limited number of experimentally sampled points.
One approach consists in fitting the response to the formula derived from
 a specific theoretical model, such as leaky integrate-and-fire neuron
 [[citep:Rauch2003,Lundstrom2009a]]. This strategy has three drawbacks: 1)
 the complexity of the analytical formula requires a careful numerical
 determination and thus render fitting procedures non trivial, 2) it
 does not generalize easily to biophysically-realistic synaptic input
 (e.g. reproducing synaptic dynamics, see [[citet:Brunel1998a]]) and 3)
 the low number of parameters of simple theoretical models (e.g. a
 single spike threshold for the leaky integrate-and-fire model)
 imposes that the membrane parameters (e.g. leak conductance and
 membrane capacitance) are free parameters to have enough degrees of
 freedom.

 We propose here a different strategy: we introduce a flexible
 analytical template fully determined by membrane parameters, which
 are experimentally measured, and some free parameters, which can be
 fitted using a simple two-step minimization procedure.

 The basis for the template rely on a simple estimate, analogous to
 [[citet:Amit1997]], for the firing rate response of the LIF model:

#+NAME: eq:template
\begin{equation}
  \nu_\mathrm{out} = \frac{\textrm{Pr}(V>V_\mathrm{thre})}{\tau_V} = 
\frac{1}{2\,\tau_V} \cdot 
\mathrm{Erfc}(\frac{V_\mathrm{thre}-\mu_V}{\sqrt{2} \, \sigma_V})
\end{equation}

 It is obtained heuristically by splitting the time axis in bins of
 length $\tau_V$, the spiking probability is then the probability that
 the membrane potential is above the threshold V_{thre} (see
 Methods[[sec:simple-approx]]). In comparison with earlier approach
 [[citep:Amit1997]], we take here the global autocorrelation time instead
 of the membrane time constant. We used this approximation as a
 baseline trend for the firing rate response and the properties of an
 individual cell will be described by deviations from this baseline
 behavior.

 We found that those deviations could be accurately accounted for by
 replacing the hard threshold of the approximation $V_\mathrm{thre}$ by
 a linear phenomenological threshold:

#+NAME: eq:linear-threshold
\begin{equation}
  \begin{split}
   V_\mathrm{thre}^\mathrm{eff} & (\mu_V, \sigma_V, \tau_V^N) = P_0 + \\
   & P_\mu \, \frac{\mu_V - \mu_V^0}{\delta \mu_V^0} +
   P_\sigma \, \frac{\sigma_V - \sigma_V^0}{\delta \sigma_V^0}
 + P_\tau \, \frac{\tau_V^N - \tau_V^{N0}}{\delta \tau_V^{N0}}
 \end{split}
\end{equation}

The quantities: \( ( \mu_V^0, \delta \mu_V, \sigma_V^0, \delta
\sigma_V, \tau_V^{N0}, \delta \tau_V^N ) \) are constant rescaling
factors of the (\mu_V, \sigma_V, \tau_V^N) space, see
Methods[[sec:fitting]].

A practical advantage of the template (Equation [[eq:template]]) is that,
given some data \(\nu_\mathrm{out}(\mu_V, \sigma_V, \tau_V^N)\), we
can invert the equation to get the phenomenological threshold as a
function of the output firing rate:

#+NAME: eq:effective-threshold
\begin{equation}
\begin{split}
 V_\mathrm{thre}^\mathrm{eff}( & \nu_\mathrm{out}, \mu_V, \sigma_V, \tau_V^N) = \\ & \sqrt{2} \, \sigma_V \, \mathrm{Erfc}^{-1}(2 \, \tau_V^N \, \tau_m^0 \, \nu_\mathrm{out}) +\mu_V, \, \,  \forall \, \nu_\mathrm{out} > 0
\end{split}
\end{equation}

Where Erfc^{-1} is the inverse of the complementary error function.

 We used this property to design the final fitting procedure: given
some data \(\nu_\mathrm{out}(\mu_V, \sigma_V, \tau_V^N)\), we
calculate the phenomenological threshold data using Equation
[[eq:effective-threshold]] and fit coefficients P_0, P_{\mu_V},
P_{\sigma_V}, P_{\tau_V} by linear regression. Then starting from
those coefficients we perform a non-linear least-square fitting. Those
two steps guarantee that the non-linear optimization starts from a
good initial guess and ensures that the gradient-descent method
converges close to the global minimum.


** Firing rate response of theoretical models

#+NAME: fig:model-response-and-fit
#+ATTR_LATEX: :float multicolumn
#+CAPTION: *The analytical template (Equations [[eq:template]] and [[eq:linear-threshold]]) can capture the firing rate response of various theoretical models.* Shown for the Leaky Integrate and Fire model (LIF) with V_{thre}=-47mV (kept for all following models), the EIF with \(k_a=2\mathrm{mV}\), the sfaLIF  with \(b=20\mathrm{pA}\), the iLIF with  \(a_i = 0.6\) and the iAdExp model that combines all the previously mentioned mechanism with \(k_a=2\mathrm{mV}, b=6\mathrm{pA}, a_i = 0.6\). *(A)* Response of the models to a current step. Plain line: response to depolarizing current step, dashed line: response to hyperpolarizing current step. For the iLIF and iAdExp models, we show in red the dynamics of the threshold \theta(t). *(B)* Firing rate response in the (\mu_V, \sigma_V) space. Color indexes variation of the global autocorrelation ratio $\tau_V/\tau_m^0$. *(C)* Projections along the standard deviation \sigma_V axis for different mean polarization levels \mu_V. Data (points) and fitted analytical template (thick transparent lines). Note the shifts in the scanned $\mu_V$ domain to reach a comparable firing range despite a reduced excitability (see main text). *(D)* Phenomenological threshold V_{thre}^{eff} that leads to the fitted firing response, the coefficients of the linear functions can be found in Table [[table:Figure-1]].
[[file:./figures/template_fit_models.pdf]]

We start by demonstrating the accuracy and flexibility of this
phenomenological description on the firing rate response for various
theoretical models (Figure [[fig:model-response-and-fit]]).

The model considered in this study is the inactivating adaptative
exponential and fire (Methods[[sec:theoretical-models]]), which extends
the model of [[citet:Brette2005a]] by adding an inactivation mechanism
[[citep:Platkiewicz2011]]. Several widespread theoretical models are
special cases of this model: the leaky integrate and fire (LIF), the
exponential integrate and fire (EIF, [[citet:Fourcaud-Trocme2003]]), the
inactivating leaky integrate and fire (iLIF, [[citet:Platkiewicz2011]]). We
also define a LIF model with spike-frequency adaptation only (sfaLIF).

We show on Figure [[fig:model-response-and-fit]] that the template is able
to describe the firing rate response of those various theoretical
models. The impact on firing of those different biophysical properties
of those models could all be accurately captured by differences in the
linear phenomenological threshold (Figure
[[fig:model-response-and-fit]]D).

We compared the four-parameter description to simpler and more complex
models in which the phenomenological threshold is: constant (1
parameter), linear function (4 parameters) or second-order polynomial
of \mu_V, \sigma_V and \tau_V^N (10 parameters). The goodness to fit
of the single-parameter description was 84.6% \pm 8.9; it increased to
99.0% \pm 0.5 for the four-parameter description; and then to 99.6%
\pm 0.2 for the quadratic phenomenological threshold with 10
parameters. We conclude that the four-parameter description offers a
good compromise between goodness-to-fit and number of parameters and
will consequently avoid over-fitting of the experimental data.

#+NAME: table:Figure-1
#+CAPTION: *Fitted coefficients of the linear phenomenological threshold for the theoretical models shown in Figure [[fig:model-response-and-fit]]* 
| model | \(P_0\)(mV) | \(P_\mu\)(mV) | \(P_\sigma\)(mV) | \(P_\tau\)(mV) |
|-------+-------------+---------------+------------------+----------------|
#+INCLUDE: ../tables/model_fitted_coeff.org
|-------+-------------+---------------+------------------+----------------|

In absence of active mechanisms, membrane potential fluctuations are
statistically identical in all theoretical models (by design, they are
the same leaky RC circuit). The active mechanisms may nonetheless have
an impact on the membrane potential fluctuations themselves and will,
by this mean, impact the firing response. In our description, those
effects are captured in the dependency of phenomenological threshold on input variables. For example,
the stationary spike-frequency adaptation level induces a net
hyperpolarizing current, which, in our description, leads to an
increased phenomenological threshold (sfaLIF vs. LIF in Figure
[[fig:model-response-and-fit]]D).


** Link between the biophysical properties and the characteristics of the firing rate response in theoretical models
<<sec:sensitivities>>

#+NAME: fig:illustration-sensitivities
#+ATTR_LATEX: :float multicolumn
#+CAPTION: *Extracting the mean properties of a single neuron response: excitability and sensitivities to the variables of the /fluctuation-driven/ regime*. *(A)* Illustration for the LIF model. From the fitting procedure we obtain an analytical description of the firing rate response (center plot). We focus the analysis on the domain $\mathcal{D}$ of the low rate fluctuation-driven regime (see main text[[sec:sensitivities]]), its extent is delimited by the white square in the bottom and top-right insets. The mean phenomenological threshold in the $\mathcal{D}$ domain quantifies the excitability (top left: large dashed line). Then for each variable (top right: \tau_V^N, bottom left: \sigma_V, bottom right: \mu_V), we show the projections of the firing response along this dimension for different combinations of the two other variables within the $\mathcal{D}$ domain (dotted lines). The mean derivative (represented by arc angle and large dashed line) with respect to the variable in x-axis over different combinations of the remaining variables quantifies the mean sensitivity to this variable. *(B)* Excitabilities for the LIF, EIF, sfaLIF and iLIF models (parameters as in Figure [[fig:model-response-and-fit]]). *(C)* Mean sensitivities to $\mu_V$. *(D)* Mean sensitivities to $\sigma_V$. *(E)* Mean sensitivities to $\tau_V / \tau_m^0$ for the four models.
[[file:./figures/illustration_excitability_sensitivities.pdf]]

To capture the particular features determining the properties of
neuronal computation in the fluctuation-driven regime, we now turn to
analyzing firing rate responses of the models.  We define four simple
quantities that provide a reduced description of the response of a
single neuron: a mean excitability (mean phenomenological threshold)
and average sensitivities to variations of mean \mu_V, standard
deviation \sigma_V and speed of the fluctuations \tau_V^N. These
quantities were average for all combination of the three input
variables consistent with awake-like conditions (low-rate, 1 - 15 Hz,
fluctuation-driven regime, $\mathcal{D}$ domain in Figure
[[fig:illustration-sensitivities]]).

 The LIF model provides a basic picture for the firing
 rate response (see LIF in Figure [[fig:model-response-and-fit]] and
 Figure [[fig:illustration-sensitivities]]A). Spiking in the LIF model increases with mean
 depolarization and the standard deviation (bottom panels in Figure
 [[fig:illustration-sensitivities]]A), while it decreases with the global
 autocorrelation time (top right panel in Figure
 [[fig:illustration-sensitivities]]A). More sophisticated biophysical
 mechanisms implemented in the considered theoretical models
 (exponential activation, adaptation, etc.) affect those baseline
 characteristics.  First of all, such mechanisms suppress spiking and
 therefore reduce the mean excitability of all the models (Figure
 [[fig:illustration-sensitivities]]B). The effect on average sensitivities
 is more complex.

 The substitution of the hard threshold of LIF with an exponential
 function in EIF imitates the gradual opening of sodium channels in
 time.  This property has a very strong impact on the dependency on
 the speed of the fluctuations (Figure
 [[fig:illustration-sensitivities]]E). In contrast to LIF, fast
 fluctuations do not lead to an increase of spiking. This effect,
 which occurs due to the inability of smooth sodium activation curve
 to extract fast varying fluctuations [[citep:Fourcaud-Trocme2003]], is
 well captured by our analysis: the sensitivity to \tau_V^N is much
 reduced for the EIF with respect to the LIF model.

 The spike frequency adaptation of sfaLIF reproduces the effect of a
 calcium-dependent potassium current (Im current) that tend to
 hyperpolarize neocortical pyramidal neurons at each spike occurrence
 [[citep:McCormick1985]]. This is an effect that attenuates firing and
 because it is proportional to firing itself we expected it would
 reduce the dependencies to all variables. Indeed the sensitivities to
 \mu_V and \sigma_V are strongly attenuated with respect to LIF
 (Figure [[fig:illustration-sensitivities]]C-D). In contrast, the
 sensitivity \tau_V^N is only mildly affected. The temporal dynamics
 of the hyperpolarizing current (\tau_W=500ms) impedes short
 inter-spike intervals in the output spike train, consequently slow
 fluctuations are more strongly dampened than fast fluctuations which
 restores the sensitivity to \tau_V^N (Figure
 [[fig:illustration-sensitivities]]E).

 The iLIF model reproduce the fast inactivation properties of sodium
 channels (see [[citet:Hille2001]] for a review). Close to threshold,
 sodium channels tend to rapidly inactivate (\tau_{inact}=5ms). This
 mechanism clearly favors fast and high amplitude fluctuations, which
 allow to trigger a spike before the channels become
 unavailable. Indeed, the sensitivity to \sigma_V and \tau_V^N is
 strongly enhanced (see Figure [[fig:illustration-sensitivities]]D-E).


** Response of juvenile mice layer V pyramidal neurons /in vitro/ with the perforated-patch technique
<<sec:exp-charact>>

#+NAME: fig:exp-charact
#+ATTR_LATEX: :float multicolumn
#+CAPTION: *The exploration of a physiologically-relevant space in layer 5 pyramidal neurons of juvenile mice*. From *B* to *E*, an example of a single cell. *(A)* A typical layer 5 pyramidal neuron in the primary visual cortex of juvenile mice. Picture from additional experiments: marking with 2\% Biocytin (Sigma Aldrich) in whole cell configuration. *(B)* After diffusion of the perforant molecule toward the patch of membrane, a step voltage clamp protocol estimates the quality of the seal and perforation (see details in the Methods[[sec:electrophy]]). *(C)* A step current clamp protocol estimate the passive membrane properties. Those properties are used by the stimulation protocols to constrain the V_m fluctuations (see Methods[[sec:stimulation-design]]). *(D)* All along the recording, we monitor the cellular properties: the resting membrane potential $E_\mathrm{L}$, the membrane resistance $R_\mathrm{m}$ and the variations of the firing rate with respect to the stationary behavior $\mathrm{CV}_\nu$ (see details in the main text[[sec:exp-charact]] and in the Methods[[sec:monitoring]]). The smoothened data (red curve) show the global trend, it removes the measurement error due to the short sampling time for $R_\mathrm{m}$ and $E_\mathrm{L}$ (see *E*), for $\mathrm{CV}_\nu$, it removes the intrinsic spiking irregularity. For the $\mathrm{CV}_\nu$ curve we have added the standard deviation (mean \pm std in red) for comparison with a stationary Poisson process (mean \pm std in black). *(E)* Sample of the membrane potential $V_\mathrm{m}$, the injected current $I$ and the total conductance $\mu_G$ at the beginning of the recording (left,t=17.7min, blue star in *D*) and one hour after (right, t=71.8min, red star in *D*). Within an episode, we scan one combination of the (\mu_V, \sigma_V, \tau_V^N) variables. For example, the middle episode corresponds to the most depolarized level \mu_V (hence the lower spike amplitude due to Na inactivation) with the fastest fluctuations \tau_V^N (i.e. an high input conductance \mu_G, also shunting the spikes, see the strong opposite current) and an intermediate variance $\sigma_V$. In between the two first episodes, one can see rest period (to monitor $E_\mathrm{L}$) followed by a current pulse (to monitor $R_\mathrm{m}$).
[[file:./figures/experimental_system.pdf]]

We now use the above analytical tools to determine experimentally firing rate responses /in vitro/.
Scanning the response of neocortical neurons in the fluctuation-driven
regime is experimentally challenging because it is characterized by an
irregular firing at low rates (\sim 0.1-20 Hz). To obtain a meaningful
estimation of the firing rate response we need long and stable
recordings [[citep:Rauch2003,Kondgen2008a]].  Both to obtain this stability
and to ensure the integrity of the intracellular medium (in particular
to maintain a physiological Ca^{2+} dynamics), we chose the
/perforated patch/ technique [[citep:Rae1991,Lippiat2008]], in which
electrical access is obtained by inserting a conducting pore
(Amphotericin B protein permeant only to monovalent ions) in a patch
of membrane [[citep:Wendt1992,Kyrozis1995]].  Although the technique may
sometimes limit the quality of the electrical access to the cell, we
achieved very low ratios between the access resistance and the
membrane resistance (4.7 \pm 2.6 %, see also [[citet:Rae1991]]), thus
allowing for reliable use of the /dynamic-clamp/ technique
[[citep:Destexhe2009]].

We monitored the stability of recordings by means of three
quantities: 1) the resting membrane potential, 2) the membrane
resistance and 3) the variations of the firing rate probability and
formulated strict criteria for the stability of the recordings (see
Figure [[fig:exp-charact]]E).

The resulting dataset contains n=30 cells, it totals to 65455 spikes
fired at an average frequency of 3.62Hz, i.e. within the low-rate,
fluctuation-driven regime defined above (1 - 15 Hz). This relatively
large amount of data was necessary to extract the biophysical
relations between the fluctuations properties and the stationary
firing rate.

#+NAME: fig:data-response-and-fit
#+ATTR_LATEX: :float multicolumn
#+CAPTION: *Characterization of the firing rate response of the recorded neocortical pyramidal neurons*. *(A)* Four examples of the firing rate response of single neurons, data (diamonds, error bars indicate variability estimated as the standard deviation from responses to multiple trials where available) and fitted template function (plain line), the cells are indexed from 1 to 4 to identify them in the heterogeneity analysis (Figure [[fig:cellular-heterogeneity]]). *(B)* For 21 neurons scanned with at least of 70 different combinations of input statistics, we split the dataset into two and investigate the similarity of the coefficients between the two subsets. The relatively high and significant (p<0.05, Pearson correlation) correlation coefficients between characterizations in the first and second datasets indicate a robust characterization of the firing rate response.
[[file:./figures/cellular_examples.pdf]]


We investigated whether the combination of the analytical template
(and its fitting procedure) with our experimental recording protocols
was able to produce a reliable characterization of the firing rate
response of layer V neocortical neurons in juvenile mice visual
cortex.

For each of the n=30 cells, we obtained a given scan of the \(\mu_V,
\sigma_V, \tau_V^N \) space and applied our fitted procedure. We show
the data and the fit for four examples in Figure
[[fig:data-response-and-fit]]. The goodness-to-fit of our template was
high (goodness-to-fit of 88.6% \pm 9.4, compared to only 38.4% \pm
35.3 for the constant threshold and 90.6% \pm 9.2 for the quadratic
phenomenological threshold), the small divergence is due to intrinsic
irregularity of the low-rate spike process (sampled over 5 s per
episode, Figure [[fig:exp-charact]]E). In spite of this variability, the
linear threshold averages the intrinsic firing irregularity and
produces a reliable characterization of the firing rate response.

To quantify the robustness of the experimental characterization, we
splitted the measurements into two sets and investigated whether the
first half of data  would give the same phenomenological threshold as
the second half. We found a good agreement if the number of
scanned configuration of input space (\mu_V, \sigma_V, \tau_V) was
n_{points} $\geq$ 70 (Pearson correlations, c>0.8 and p<1e-5 for the
correlations between first and second half of data, Figure
[[fig:data-response-and-fit]]B). The high Pearson correlations between the
response characteristics in the two subsets indicates that the characterization is robust for n_{points} $\geq$ 35 scanned combinations of input parameters. Among the 30 cells used for further
analysis, the cell with the minimum number of points had n_{points}=42
scanned combinations meeting the above criterion for the robustness.


** Single neurons show strongly heterogeneous firing rate responses
<<sec:heterogeneity>>

A striking feature in the response of the recorded cells is the
differences in their response. 

#+NAME: fig:cellular-heterogeneity
#+ATTR_LATEX: :float multicolumn
#+CAPTION: *Heterogeneity and underlying structure of the firing response of neocortical cells* *(A)* Histogram over recorded cells of the mean excitabilities and sensitivities to the variables of the fluctuations. The dashed color lines show the values of theoretical models for comparison. *(B)* Scatter plot of the mean excitability and sensitivities to the variables of the fluctuation-driven regime, we highlighted the cells shown in Figure [[fig:data-response-and-fit]] with larger markers. *(C)* Principal component analysis, in the inset, the vector coordinates of the two first components 
[[file:./figures/cellular_heterogeneity.pdf]]

We illustrate this property on the four examples shown in Figure
[[fig:data-response-and-fit]]A. Cells 1 and 4 show a very
strong dependency on speed of the fluctuations \tau_V, whereas cells 2 and 3 are almost insensitive to
to this parameter (different colors in [[fig:data-response-and-fit]]A). The dependency on the standard deviation of fluctuations \sigma_V is steeper 
for cell 2 than for 3 and 4. Also the sensitivity to \mu_V
seems to be variable, a 10 mV depolarization has stronger effect
on responses of cell 4 than 3. Finally, the
cell excitabilities are also highly variable, so that they reach the 1-15Hz
firing range at various depolarization levels (e.g. compare cell 2 and 3).
Similar differences are present in all recorded pyramidal cells
(Figure [[fig:cellular-heterogeneity]]A).

This strong heterogeneity raises the question whether there is an
underlying structure in the variations of the characteristics of the
firing rate response and how could it be explained by diverse
biophysical mechanisms. 

First, when plotted in four-dimensional space of the firing response
characteristics the data did not seem to distribute into distinct
clusters (Figure [[fig:cellular-heterogeneity]]B). Presented on two
dimensional projections, the excitability and sensitivities to input variables of different cells co-vary (Pearson correlation, $c$, Figure
[[fig:cellular-heterogeneity]]B). We then looked for the four-dimensional
structure of those co-variations in the response characteristics by
means of a principal component analysis (Figure
[[fig:cellular-heterogeneity]]C). No single co-variation of the
sensitivities could explain a strong percentage of the observed
heterogeneity, suggesting that the correlation structure is weak.

Nonetheless, two vectors explained 75% of the variations in the
data. The first vector corresponds to a co-variation of the
sensitivities to mean and amplitude of the fluctuations. This
co-variation can be achieved in the sfaLIF model, varying the weight
of spike frequency adaptation concomitantly varies the sensitivities
to \mu_V and \sigma_V (Figure [[fig:biophysics-explain-heter]]C). The
second vector corresponds to a co-variation of a decrease in the
excitability and an increase in the sensitivity to the speed of the
fluctuations. The variability in excitabilities is quite remarkable,
to reproduce it in the LIF model one needs variations of the threshold
V_{thre} that spans nearly 15 mV (see Figure
[[fig:biophysics-explain-heter]]). The variability in the sensitivity to
\tau_V covers a wide range of parameters in theoretical models, from
an EIF model with a smooth curve (k_a=2mV) to a strongly inactivating
iLIF model (a_i=0.7). Increasing the threshold while increasing the
impact of sodium inactivation and increasing the sharpness of the
sodium activation curve would therefore reproduce the second component
of the principal components analysis.

#+NAME: fig:biophysics-explain-heter
#+ATTR_LATEX: :float multicolumn
#+CAPTION: *Variations in the expression of biophysical mechanisms explain the observed cellular heterogeneity in their firing rate response*. *(A)* Increasing the threshold V_{thre} of the LIF model. Note that this only affects the excitability and negligibly the sensitivities to \mu_V, \sigma_V and \tau_V^N. *(B)* Decreasing the sharpness of the sodium activation curve in the EIF model, k_a=0mV corresponds to the LIF model, k_a=3.7mV corresponds to a very smooth activation. Note the strong impact on the sensitivity to \tau_V^N. *(C)* Increasing spike frequency adaptation in the sfaLIF model, b=0 mV corresponds to the LIF model, b=35pA corresponds to a strongly adapting model. Note the concomitant variations of the sensitivities to \mu_V and \sigma_V.  *(D)* Increasing sodium inactivation in the iLIF model, a_i=0 corresponds to the LIF model, a_i=0.7 corresponds to a strongly inactivating model. Note the strong impact on the increase in sensitivity to sigma_V and \tau_V^N. *(E)* Histogram of the data from the n=30 neurons. 
[[file:./figures/biophysics_explain_heterogeneity.pdf]]


* Discussion

We studied systematically the firing rate response of different
neuronal models as well as /in vitro/ layer V pyramidal cells as a
function of the three variables composing our definition of the
/fluctuation-driven/ regime.

Compared to previous studies [[citep:LaCamera2008]], we focused on the low
rate regime and we extended the domain of somatic /in vivo/-like
conditions. In particular, we investigated the dependency on the
firing rate for high somatic conductance and low autocorrelation time
of the membrane potential fluctuations. Scanning the response to low
autocorrelation time allowed to highlight the impact of sodium
inactivation because this is the regime where the temporal dynamics of
this features is likely to play (\tau_{inact} \sim 5\mathrm{ms}).

We formulated a two-step procedure to circumvent the issue of
spatially distributed inputs in neocortical neurons where the
intermediate quantities are the properties of the V_m fluctuations at
the soma. Other investigators studied the response to the noisy
current input properties at the soma and then addressed the problem of
how dendritic integration shape the properties of this current
[[citep:LaCamera2008,Giugliano2008]]. Our approach can be seen as a way to
include the mean conductance effect due to changes in background
synaptic activity. The reason we presented the data as a function of
the V_m fluctuations properties and not the quantity that the
experimentalist actually controls (the current and the conductance) is
that it allows to compare individual cells and that the spiking
response is dominated by subthreshold integration effects, e.g. for a
same variance of input current, an increasing conductance would
decrease the V_m fluctuations amplitude by shunting effects
[[citep:Kuhn2004]]. The effects of the spike-related mechanisms are then
difficult to de-intricate from those subthreshold effects. Here, we
used calculus to design a stimulation protocol that allows to control
the fluctuations and therefore to focus on understanding the single
neuron computation on top of the fluctuations properties.

Starting from a simple approximation, we showed that bringing the
problem into a phenomenological threshold space was a simple way to
describe the firing rate response of neocortical neurons. Other
investigators already reported that a shift in the threshold was a
convenient way to account for increasing biophysical complexity
[[citep:Brunel1998a,Platkiewicz2010]]. Unlike the two mentioned studies,
the form of our phenomenological threshold was not derived
mathematically (it was arbitrarily taken as linear) but we believe
that the descriptive power of this very simple form further confirms
the idea that the threshold space is a convenient space to work in.

We showed that this template is able to describe the response of
neuronal models of varying complexity. We then used this simple
description to design a robust characterization of the firing rate
response of single neurons experimentally. This approach, combined
with the long and stable recordings provided by the perforated patch
technique, was our way to circumvent the experimental and theoretical
difficulties of assessing a relevant firing rate response in a low
rate irregular firing regime.

We now discuss the biophysical mechanisms relevant for the firing rate
response of layer V pyramidal cells in juvenile mice visual cortex.

First, spike frequency adaptation was shown to be an important
mechanism to the firing rate response. Notably, all models lacking
spike frequency adaptation (LIF, EIF, iLIF) had a sensitivity to \mu_V
higher than all recorded cell. This mechanism is therefore crucial to
reproduce the attenuated sensitivity to depolarizations of layer V
pyramidal cells in mice visual cortex.

Many cells showed a weaker sensitivity to the speed of the
fluctuations than the LIF model (n=20 out of 30). This could be
reproduced in theoretical models by implementing a smoother activation
curve for the sodium channels (EIF models of varying sharpness). This
observations contrasts with reports from studies in more mature
pyramidal neurons in rat neocortex [[citep:Kondgen2008a,Ilin2013]], where
it was found that pyramidal cells could have a very sharp activation
curve that would enable them to extract very fast input.
Nevertheless, even at the soma, the neurons of our recordings show a
rather smooth activation curve: k_a \sim 1.5 mV (not shown) from the
dynamic I-V curve analysis [[citep:Badel2008]] rendering this possibility
unlikely.

Surprisingly some cells showed a stronger sensitivity to the speed and
amplitude of the fluctuations than the LIF model (n=10 out of 30). By
penalizing slow and low amplitude fluctuations, sodium inactivation
seem to be able to explain this phenomena. Our observation is thus
analogous to the phenomena described in [[citet:Fernandez2011]] for
pyramidal cells in rat CA1, where the authors found that a high
conductance state (corresponding to fast fluctuations in our study)
could evoke more spikes than a low conductance state (slow
fluctuations here). Their study provides evidence for the role of fast
sodium inactivation in the sensitivity to the speed of the
fluctuations and is therefore compatible with our modeling
results. Because of its role in promoting large amplitude and/or fast
fluctuations, sodium inactivation seems to be a key property in
shaping the input-output properties of layer V pyramidal cells in the
fluctuation-driven regime.

Finally, we did not discuss the impact of other subthreshold
non-linearities usually present in pyramidal cells such as the Ih
current. This mechanisms is weakly expressed in the pyramidal cells of
our recordings (see response to current steps in Figure
[[fig:exp-charact]]C). Nevertheless, we investigated its effect on the
firing response (not shown). Because of its high pass filtering
behavior, it would have an effect very similar to the one of sodium
inactivation: penalizing slow fluctuations and therefore increasing
the sensitivity to \tau_V.

In conclusion, our study shows that the spiking response of cortical
neurons is highly inhomogeneous in juvenile mice visual
cortex. Because we see no evidence for any type of invariance of
cellular responses (after rescaling by membrane parameters), this
aspect of cellular heterogeneity should then be considered as an
additional component to the diversity in cell size and shape
classically reported in cerebral cortex.

Those diverse firing responses will consequently strongly affect
population rate dynamics in the low rate fluctuation-driven
regime. Such results and measurements should be incorporated into
mean-field descriptions of cortical dynamics to understand the
properties emerging at the network level , which constitute the main
perspective for future continuation of the present work.


* Material and Methods 
\small


** Experimental preparation
<<sec:exp-prep>>

Experimental procedures with animals were performed following the
instructions of the European Council Directive 2010 86/609/EEC and its
French transposition (Décret 2013/118). Swiss wild-type mice of either
sex, 8–13 days old, were anesthetized with inhaled isoflurane and
decapitated, their brain was rapidly removed and immersed in cold
“cutting” solution (\sim 4^{o}C) containing the following (in mM): 110
Choline Chloride, 2.5 KCl, 1.25 NaH2PO4, 26 NaHCO3, 8 MgCl2, 1 CaCl2,
10 glucose, pH equilibrated to 7.3 with O2/CO2 (95\%/5\%). Coronal
slices (300 $\mu\mathrm{m}$ thick) were prepared with a vibratome
(Leica VT1200 S, Leica Microsystems) and stored at room temperature in
oxygenated aCSF containing the following (in mM): 126 NaCl, 2.5 KCl,
1.5 NaH2PO4, 26 NaHCO3, 2 MgCl2, 2 CaCl2 and 10 glucose, pH 7.4. The
slices were then transferred to the recording chamber (perfused with
the same solution) where the temperature was maintained at
34^{o}C. Slices containing primary visual cortex were taken as the
first four slices containing brain cortex starting from the most
caudal one.


** Electrophysiological recordings
<<sec:electrophy>>

We performed intracellular recordings of visually identified pyramidal
cells located in the layer V of mice cortex using the perforated patch
technique.

Patch electrodes (tip resistance: 1.5–2.5 $\mathrm{M}\Omega$) were
pulled on a Sutter P-1000 apparatus (Sutter Instruments) and filled in
a two step procedure. The pipettes were pre-filled with a solution
containing the following (in mM): 130 K-Gluconate, KCl 7, NaCl 1,
MgCl2 4, HEPES 10, pH adjusted to 7.3 with KOH (osmolarity 260
mOsm). The pipette was then back-filled with the same solution to
which was added Amphotericin-B (Sigma Aldrich) previously dissolved in
DMSO, the final concentration of Amphotericin-B was 60
$\mu\mathrm{M}$. The reason for this two step procedure is to allow a
current flow out of the pipette (to preserve the tip from dirt)
without pouring the perforant onto the target cell during the pipette
approach. The perforation could therefore happen only after diffusion
of Amphotericin-B through the "clean" solution, this usually took 5-10
minutes after the pipette filling, thus allowing the cell-attached
configuration to form in absence of the perforant molecule.

We recorded from n=30 cells. After perforation, the access resistance
R_S was 14.7M\(\Omega\) \(\pm\) 6.9. This value was plugged in into
the amplifier-build bridge compensation system during the
current-clamp recordings. At -75 mV, the recordings exhibited a leak
current of -31.9 pA \(\pm\) 26.8 (minimum observed resting potential:
-76 mV), this current value was then set for each neuron as the
holding current during the recording. Recorded pyramidal cells had an
input resistance R_m of 355.9 M$\Omega$ \(\pm\)184.1 and a membrane
time constant at rest of : 31.4ms \(\pm\) 12.0. Recordings lasted 36.7
min \pm 20.9. In the absence of current injection, cells presented a
quiescent activity.

The liquid junction potential was measured to be 6 mV and membrane
potential recordings were corrected accordingly. Note that there might
be anyway an unknown constant shift in the voltage value because the
Amphotericin-B pores are selective channels (so that a non-zero
reversal potential could appear if the cellular medium and our pipette
medium are different). The absolute values of the membrane potential
presented here should therefore be interpreted carefully (but this
would only affect the \( \langle V_\mathrm{thre}^\mathrm{eff}
\rangle_\mathcal{D} \) quantity reported in this study).



** Measuring firing rate
<<sec:measured-quant>>

 We measured the firing rate simply by counting spikes over a fixed
 time window. Spikes were detected as a upward crossings of -20mV. The
 first 100ms we removed to avoid transient effects associated to the
 membrane potential rise. The duration of the stimulation was usually
 5s, therefore the minimum (non zero) rate was 0.2 Hz. Also an online
 analysis was counting spikes and the stimulation was stopped when
 \sim 20 spikes were reached (see in Figure [[fig:exp-charact]]E, the
 middle episode is shorter than the two other ones), this to avoid
 spending to much recording time in the high firing rate range.


** Dynamic-clamp
<<sec:dynamic-clamp>>

Our dynamic-clamp system consists of an Intel Quad-Core computer
equipped with an acquisition card (NI PCI-6251 ADC/DAC,Mseries,
National Instruments) connected to the amplifier operating in
current-clamp mode. The dynamic-clamp software is based on a custom
ADC/DAC (analog-to-digital/digital-to-analog) program used for data
acquisition and analysis [Elphy2, developed at Unité de Neurosciences,
Information et Complexité (UNIC) by Gérard Sadoc] and interfaced with
the =NEURON= simulator version 6.0 (Hines and Carnevale,
1997). =NEURON= was modified and recompiled to run under the INtime
(TenAsys), a Real Time Operating System running alongside Microsoft
Windows.  The recordings were performed using a Multiclamp 700B
amplifier (Molecular Devices). Stimulation protocols were run in real
time with the acquisition card at 10 kHz. Acquisition and filter
frequencies were set at 10 and 4 kHz, respectively. An unfiltered copy
of the membrane potential signal was feeding the /dynamic clamp/
system.


** Single compartment approximation
<<sec:single-comp>>

Both for the experimentally recorded neurons and for the theoretical
models, we will use the single compartment membrane equation. The
passive properties of a neuron are therefore described by a leak
conductance g_L, a capacitance C_m and a resting potential E_L. With
an additional current $I(V, t)$, the membrane potential thus follows:

#+NAME: eq:membrane-eq
\begin{equation}
  C_\mathrm{m} \frac{dV}{dt} = I(V, t) + g_\mathrm{L} \, (E_\mathrm{L} - V)
\end{equation}

Passive properties were fitted from the response to a hyperpolarizing
current step for the recorded neocortical neurons in the subthreshold
domain (around -75 \pm 5mV).

Though this approximation was found to be satisfactory (Figure
[[fig:exp-charact]]C), monitoring possible deviations is important in this
study as the approximation is used to shape the fluctuations of the
membrane potential. We therefore performed a cell-by-cell
quantification of the accuracy of the approximation as follows. We
take the protocols that were used to determine the membrane
properties: prior to each protocol, we recorded and averaged the
response to 10 current pulses of $\sim$ 500ms and of $\Delta I \sim$
15pA amplitude, not the (noisy) continuous monitoring presented in
Figure [[fig:exp-charact]]. We average over trials the membrane potential
response and fit an exponential curve to this mean response
$V_\mathrm{sc}^\mathrm{fit}(t)$, we get a membrane time
$\tau_\mathrm{m}^0$ and a membrane resistance $R_\mathrm{m}^0$. We
define the residual trace as the normalized absolute difference
between the fit and the trace :

\begin{equation}
\mathrm{Res}(t) = \big| \frac{  V(t) - V_\mathrm{sc}^\mathrm{fit}(t)}{R_m^0 \Delta I}  \big| 
\label{eq:residual-single-comp}
\end{equation}

 Now we quantify the accuracy of the single-compartment approximation
 by taking the (normalized) integral over 7 membrane time constant of
 the residual trace.
 # (see bottom traces in [[fig:single-comp-approx]]B and [[fig:single-comp-approx]]C).

\begin{equation}
C_\mathrm{sc} = \int_{t_0}^{t_0+7 \, \tau_m^0} \frac{dt}{7\,\tau_m^0}
\mathrm{Res}(t)
\label{eq:accuracy-coeff-single-comp}
\end{equation}

 The two normalizations (by membrane resistance and membrane time
 constant) were performed to yield comparable quantities for different
 membrane parameters.

 We investigated whether the quality of the approximation had an
 impact on the excitability and sensitivities presented in the
 Results, we found no significant correlations between those
 quantities and the quality of the recordings (c<0.2 and p>0.2 for all
 characteristics, Pearson correlations), thus suggesting that the
 results of our study were not impacted by deviations from the single
 compartment approximation.


** Global autocorrelation time
<<sec:autocorrel-def>>

We present here a theoretical estimate for the speed of the membrane
potential fluctuations.

In the case of a fluctuating synaptic input with temporal dynamics
(e.g. resulting from a shotnoise of /exponential/ synapses considered
in this study, unlike the /delta/ synapses considered in other
studies, see [[citet:Amit1997]] for an example), the autocorrelation
function is not an exponential function. Consequently, the resulting
membrane fluctuations can not be characterised by a single time
constant $\tau_V$ (see the inset in Figure
[[fig:3D-motiv]]). Nevertheless, the time constant taken from an
exponential approximation of the normalized autocorrelation function
corresponds to a first order description of the autocorrelation and
will be the main contributor to the temporal dynamics of the
fluctuations.

As a theoretical prediction for this /global autocorrelation/ time, we
take the half integral of the normalized autocorrelation correlation
function:

#+NAME: eq:Tv-def
\begin{equation}
  \tau_V = \frac{1}{2} \, \int_\mathbb{R} d \tau \frac{A(\tau)}{A(0)}
\end{equation}

where \( A(\tau) \) is the autocorrelation function of the V_m
fluctuations (see an example of \( A(\tau)/A(0) \) in Figure
[[fig:3D-motiv]]). From shotnoise theory [[citep:Daley2007]], we will obtain
the power spectral density of the V_m fluctuations \( P_V(f) \), so we
re-express the global autocorrelation time as:

#+NAME: eq:Tv-def-with-pwd
\begin{equation}
  \tau_V = \frac{1}{2} \, \big( \frac{\int_\mathbb{R} P_V(f) \, d f}{ P_V(0) } \big)^{-1}
\end{equation}

 In this study, this formula reduces to a very simple form (see next
 section). Note that the relations presented in this paper rely on the
 following convention for the Fourier transform: \( \hat{F}(f) =
 \int_\mathbb{R} F(t) \, e^{- 2 i \pi f t} \, dt\).


** A stimulation to investigate the dependency on the variables of somatic fluctuations
<<sec:stimulation-design>>

We aim at reproducing the dynamical state at the soma in the
fluctuation-driven regime by reproducing membrane potential
fluctuations with the control of the mean $\mu_V$, the standard
deviation $\sigma_V$ of the subthreshold fluctuations as well as a
global autocorrelation time $\tau_V$.

Our "input space" is already a response of the neuron, thus we need a
stimulation that would reliably produce this response. There exists
multiple types of input that would lead to a given set of the (\mu_V,
\sigma_V, \tau_V) variables. In the present study, to best
characterize the dependency on those precise variables, we wanted a
stimulation that would minimize the higher order terms appearing for
realistic synaptic inputs, e.g. when injecting excitatory and
inhibitory Ornstein-Uhlenbeck conductances
[[citep:Destexhe2001a,Fernandez2011]]. We chose the following stimulation.

The mean membrane potential is achieved through a constant current
input:
#+NAME: eq:muV-current
\begin{equation}
  I_{\mu_V} = g_\mathrm{L} \, (\mu_V - E_\mathrm{L}) 
\end{equation}

Varying the speed of the fluctuations \tau_V is achieved by changing
the total input conductance at soma \mu_G (an increasing conductance
reduces the effective membrane time constant of the membrane, events
are integrated faster and this renders fluctuations faster). The total
conductance \mu_G is changed by introducing a current I_{\mu G} of
static conductance g_S=\mu_G - g_L and of reversal potential \mu_V:

#+NAME: eq:shunting-current
\begin{equation}
  I_{\mu_G}(V) = g_S \, \big(\mu_V - V \big) 
\end{equation}

We introduce here the effective membrane time constant
\( \tau_\mathrm{m}^\mathrm{eff} = C_\mathrm{m} /(g_S + g_L) \).

An additional noisy current of zero mean creates the fluctuations
around \mu_V to control the standard deviation \sigma_V.  This current
is generated from two independent Poisson processes convolved with an
exponential kernel: one excitatory, one inhibitory. They have the same
presynaptic rate $\nu_{in}$, the same time constant for the
exponential decay $\tau_S$ and opposite current increments Q_I and
-Q_I. This corresponds to the current I_{fluct}(t):

#+NAME: eq:fluct-eq
\begin{equation}
  \tau_S \, \frac{ d I_\mathrm{fluct} }{dt} = - I_\mathrm{fluct} + Q_I
   \Big( \sum_{k} \delta (t_e^k-t) - \sum_{k} \delta (t_i^k-t) \Big)
\end{equation}

Where $\{t_{e}^k\}_{k \in \mathbb{N}}$ and $\{t_{i}^k\}_{k \in
  \mathbb{N}}$ are two sets of uncorrelated presynaptic events
generated by the frequency \nu_{in}.

A single excitatory or inhibitory post-synaptic potential event from
this input will have the following time course:

#+NAME: eq:psp-time-course
\begin{equation}
 PSP(t) = \pm \frac{ Q_I \, \tau_S \, (e^{-\frac{t}{\tau_S}} - 
 e^{-\frac{t}{\tau_\mathrm{m}^\mathrm{eff}}})}{g_L \,
 (\tau_\mathrm{m}^\mathrm{eff} - \tau_S)}
\end{equation}

From shotnoise theory [[citep:Daley2007]] (see also
[[citet:ElBoustani2009a]] for an application similar to ours), we can
obtain the power spectral density of the V_m fluctuations \( P_V(f) \)
as a response to the stimulation Equation [[eq:fluct-eq]]:

#+NAME: eq:vm-pwd
\begin{equation}
\begin{split}
 P_V(f)  = & \sum_{syn} \nu_{syn} \, \| \hat{\mathrm{PSP}}(f) \|^2 \\
 & = 2 \nu_{in} \, \frac{Q_I^2 \, \tau_S^2 / \mu_G^2 }{
 (1+4 \pi^2 f^2 \tau_S^2)(1+4 \pi^2 f^2 \tau_m^2)}
\end{split}
\end{equation}

The variance of the membrane potential fluctuations is the integral of
the power density spectrum :

#+NAME: eq:var-expr
\begin{equation}
  \sigma_V^2 = \int_\mathbb{R} P_V(f) \, df =
  \nu_{in} \cdot \frac{ (Q_I \, \tau_S)^2 }{ (\tau_m \, g_L )^2 \, 
    (\tau_S + \tau_m ) }
\end{equation}

And the global autocorrelation time takes the very simple form, see
Equation [[eq:Tv-def-with-pwd]] :

#+NAME: eq:Tv
\begin{equation}
  \tau_V = \frac{1}{2} \, \big( \frac{\int_\mathbb{R} P_V(f) \, d f}{ P_V(0) } \big)^{-1} 
  = \tau_S + \tau_m
\end{equation}

We rescale this relation with respect to the resting membrane time
constant \tau_m^0:
#+NAME: eq:TvN
\begin{equation}
  \tau_V^N = \frac{\tau_V}{\tau_m^0} = \frac{\tau_S}{\tau_m^0} +\frac{g_L}{\mu_G} 
\end{equation}

Because the mean synaptic conductance \mu_G should scale with the size
of the membrane (because of the constant surfacic density of
synapses), as does g_L (because of the constant surfacic density of
leak channels), when the presynaptic bombardment increases, it is the
rescaled quantity \mu_G/g_L that increases. Therefore we investigated
a fixed domain of the \tau_V/\tau_m^0 quantity.

Finally, the time- and voltage-dependent current $I(V, t)$ inserted
into the membrane Equation [[eq:membrane-eq]] or injected via the
dynamic-clamp technique takes the form:

#+NAME: eq:final-input
\begin{equation}
  \left\{
  \begin{split}
  & I(V,t) = I_{\mu_V} + g_S \, (\mu_V - V) + I_{fluct}(t)\\
   \tau_S \, \frac{ d I_{fluct} }{dt} & = - I_{fluct} + Q_I
   \Big( \sum_{k} \delta (t_e^k-t) - \sum_{k} \delta (t_i^k-t) \Big)
  \end{split} \right.
\end{equation}

The three variables (\mu_V, \sigma_V, \tau_V^N) are achieved through
the five variables of the input (I_{\mu_V}, g_{S}, \nu_{in}, \tau_S,
Q_I). We have two additional degrees of freedom, so 1) to force the
input to remain in the /fluctuation-driven/ regime (many events of low
amplitude) we arbitrarily set the presynaptic frequency to
$\nu_\mathrm{in}=2\mathrm{kHz}$ and 2) we fixed the current time
constant to: \tau_S/\tau_m^0=15% (i.e. \tau_S=4.5ms for
\tau_m^0=30ms).

Thus, when we want to study the firing rate response as a function of
(\mu_V, \sigma_V, \tau_V^N), with the membrane parameters (g_{L},
\tau_{m}^0, E_{L}), we send an input of the form Equation
[[eq:final-input]], where (I_{\mu_V}, g_S, \tau_S, Q_I, \nu_{in}) follow:

#+NAME: eq:conversion-rule
\begin{equation}
  \left\{
  \begin{split}
  & \tau_S = 0.15 \, \, \tau_m^0 \\
  & \nu_{in} = 2. 10^3 \\
  & I_{\mu_V} = g_\mathrm{L} \, (\mu_V - E_\mathrm{L}) \\
  & g_S = g_\mathrm{L} \, \big( (\tau_V^N - \frac{\tau_S}{\tau_m^0})^{-1} -1 \big) \\
  & Q_I = \frac{(g_\mathrm{L} +g _S) \, \sigma_V \sqrt{\tau_m^0} \sqrt{\tau_V^N}}{\tau_S \, \sqrt{\nu_{in}}} \\
\end{split} \right.
\end{equation}


** Monitoring the stability of the cellular properties
<<sec:monitoring>>

Because the stimulation depends on the membrane properties (see the
previous section[[sec:stimulation-design]]), it was crucial to insure the
stability of those properties during the experiments. We therefore
monitored the cellular properties in time in an analogous manner to
[[citet:Kondgen2008a]].

In between the episodes, we use the resting period to measure the
resting membrane potential $E_\mathrm{L}$ and we inject a short
current pulse to calculate the membrane resistance. Those quantity over time are then smoothened over a
sliding window of 20 points to remove the error introduced by the
evaluation over a rather short time window (Figure
[[fig:exp-charact]]E).

The data kept in the dataset had to keep variations within \pm 3 mV
for $E_\mathrm{L}$ and below 10 \% for $R_\mathrm{m}$.

In addition, we quantified and monitored the stability of the firing
rate response. Here, the fitted response was found to be very useful
(see Results[[sec:building-template]]). When we fit, we do not
discriminate between the early and the late measurements, the fitted
function $\mathcal{F}$ therefore provides a mean of the response
across the measurement. Then we can detect variations around this mean
behavior by computing the coefficient of variation of the response:

\begin{equation}
\label{coeff-var}
\mathrm{CV}_\nu(\vec{x}, t_i) = 
\frac{\nu_\mathrm{out}(\vec{x},t_i)-
\mathcal{F}(\vec{x})}{\sqrt{\mathcal{F}(\vec{x}) / T_i}}
\end{equation}

where $\vec{x}$ represents a combination of the input (\mu_V,
\sigma_V, \tau_V^N), $t_i$ the time of the measurement and $T_i$ the
duration of the measurement. Because of the intrinsic irregularity of
the spiking process, we expect strong fluctuations within this curve
(see Figure [[fig:exp-charact]]D), but the smoothen version of this curve
allow to detect changes on a long time scale. For example, a strong
/run-down/ would correspond to a strongly decreasing $\mathrm{CV}_\nu$
curve. The criteria to insure stability was to remain close enough
from a stationary Poisson process, i.e. the smoothen curve should not
cross \pm 1.

Given those criteria, we expect that the effect of the remaining
variability in the properties would be canceled by the randomization
of the scanned input points and the use of multiple seeds.


** Theoretical models of neurons
<<sec:theoretical-models>>

The general model considered in this study is the inactivating
Adaptative Exponential and Fire model. It is constructed by combining
the theoretical models proposed in [[citet:Brette2005a]] and
[[citet:Platkiewicz2011]].


#+NAME: eq:iAdExp
\begin{equation}
\hspace{-.3cm}
  \left\{
  \begin{split}
  & C_\mathrm{m}\,\frac{dV}{dt} = g_\mathrm{L} \,(E_\mathrm{L}-V) + I_{syn}(V,t) + k_a e^{\frac{V-V_\mathrm{thre}}{k_a}}- I_w \\
  & \tau_w \frac{d I_w}{dt} = - I_w + \sum_{t_s \in \{t_{spike}\}} b \, \, \delta (t-t_s) \\
  & \tau_i \frac{d \theta}{dt} = - \theta + a_i \, (V - V_i) \, \mathcal{H}(V - V_i)
\right.
\end{equation}

where $I_{syn}(V, t)$ is the current emulating synaptic activity that
will create the fluctuations, $I_w$ reproduces the I_m current
[[citep:McCormick1985]] and $\theta(t)$ is a variable threshold whose
temporal dynamics and voltage dependence accounts for the fast
decrease in sodium channel availability at depolarized levels
[[citep:Hille2001]].

The temporal dynamics of sodium inactivation and spike frequency
adaptation were fixed to \tau_i=5ms and \tau_w = 500ms
respectively. Also the threshold of the inactivation curve was fixed
relative to the sodium activation threshold as
\(V_i=V_\mathrm{thre}-8\mathrm{mV}\). The leak potential was set to
E_L=-70mV all along the study. All other parameters are varied along
the study (see figure legends).

 Finally, because of the variability of membrane time constants in the
 experimental data (indeed, the data show variations not only in input
 resistance, also in \tau_m^0), the comparison for the firing response
 between data and theoretical models requires a careful
 treatment. Because when the synaptic bombardment raises, the ratio of
 input conductance with respect to the leak conductance \mu_G/g_L
 raises, we scanned a fixed range in terms of \tau_V^N=\tau_V/\tau_m^0
 (see previous section[[sec:stimulation-design]]). But this means that for
 a given range of \tau_V^N=\tau_V/\tau_m^0, there will be different
 range of \tau_V when there is a change in membrane time constant
 \tau_m^0, and consequently a different range of output frequency. The
 solution that we adopted for a relevant comparison between data and
 theoretical models is to simulate the models with different membrane
 time constants \tau_m^0 reproducing the variability in experimental
 data. Only in Figure [[fig:model-response-and-fit]], a single model was
 numerically simulated with the parameters (g_L = 2.5 nS, C_m = 80pF
 to get \tau_m^0=32ms as the average of the intracellular data). For
 all other figures (Figures [[fig:illustration-sensitivities]],
 [[fig:cellular-heterogeneity]] and [[fig:biophysics-explain-heter]]), where
 the sensitivities are presented, we simulated three models, all with
 the same leak conductance g_L = 2.5 nS, but with varying capacitance
 to reach \tau_m^0 \in [20,32,44] ms to reproduce the standard
 deviation of the data (see previous section[[sec:electrophy]]). The
 presented sensitivities were then the average of the sensitivities of
 the three models. Note that, even if the scaling of the firing
 response with the resting membrane time constant is clear in
 theoretical model (\nu_{out} \propto 1/\tau_m^0 for a given \tau_V^N
 space), this effect was not significantly visible in the data
 (Pearson correlations between mean excitability and membrane time
 constants, p>0.1) presumably masked by the heterogeneity discussed in
 this paper.


** Starting from a simple approximation for the firing rate
<<sec:simple-approx>>

The starting approximation that we will use has been introduced in
[[citep:Amit1997]]. Our situation is different, we have a more complex
synaptic input but we only want the stationary firing rate, so we
justify this estimate in a more abstract manner.

If a neuron has membrane potential fluctuations described by a mean
$\mu_V$, a variance $\sigma_V$ and a typical autocorrelation time
$\tau_V$, then we can divide a time axis of length $T$ (with $T\gg
\tau_V$) into $N$ bins of length $\tau_V$. Within each of this bin, we
consider that a reorganization of the membrane potential values
occurs, then the bins can be considered independently, and in each, we
sample randomly from the Gaussian distribution defined by $\mu_V$ and
$\sigma_V$. We remain in the low firing regime (\nu_{out} \leq
30 Hz) , so that we can neglect the repolarization dynamics and
saturation effects. Then, if a spike occurs when the membrane
potential crosses a threshold $V_\mathrm{thre}^\mathrm{eff}$, the
probability to have a spike within a bin is the probability to be
above this threshold
$\mathrm{Pr}(V>V_\mathrm{thre}^\mathrm{eff})$. The number of spikes
during the time $T=N \tau_V$ is $k = N \cdot
\mathrm{Pr}(V>V_\mathrm{thre}^\mathrm{eff})$. The definition of the
stationary firing rate is $\nu_\mathrm{out}=k/T$, so that we get:

#+NAME: eq:template-2
\begin{equation}
\nu_\mathrm{out} = \frac{\mathrm{Pr}( V \geq V_\mathrm{thre}^\mathrm{eff})}{\tau_V}
\end{equation}
i.e. in the case of a Gaussian distribution for the membrane
potential:
\begin{equation}
  \nu_\mathrm{out} = \frac{1}{2\,\tau_V} \cdot 
\mathrm{Erfc}(\frac{V_\mathrm{thre}^\mathrm{eff}-\mu_V}{\sqrt{2} \, \sigma_V})
\end{equation}

where the subthreshold variables $\mu_V$, $\sigma_V$ and $\tau_V$ can
be calculated as a response to the synaptic input as detailed in the
previous section[[sec:stimulation-design]].

We will use its derivative. For a variable $x$ being either $\mu_V$,
$\sigma_V$ or $\tau_V^N$, we get:

#+NAME: eq:derivatives
\begin{equation}
\begin{split}
& \frac{\partial \, \nu_\mathrm{out} }{\partial x } = - \frac{\partial  \tau_V }{ \partial x }  \frac{ \nu_\mathrm{out}}{  \tau_\mathrm{m}^0} \, \frac{1}{\tau_V^N } + \\
\frac{ \mathrm{e}^{-(\frac{V_\mathrm{thre}^\mathrm{eff}-\mu_V}{\sqrt{2} \, \sigma_V})^2} }{ \sqrt{2\,\pi} \,  \tau_\mathrm{m}^0 \, \tau_V^N}  &  \cdot
\Big( \frac{1}{\sigma_V} (\frac{\partial \, V_\mathrm{thre}^\mathrm{eff}}{\partial x} - \frac{\partial \mu_V}{\partial x} ) - \frac{\partial \sigma_V}{\partial x} \, \frac{V_\mathrm{thre}^\mathrm{eff}-\mu_V}{\sigma_V^2} \Big) 
\end{split}
\end{equation}

where $V_\mathrm{thre}^\mathrm{eff}$ depends linearly on the
fluctuations variables (Equation [[eq:linear-threshold]]).


** Fitting
<<sec:fitting>>

To render the fitting the phenomenological threshold easier, we
insured that the linear coefficients of Equation
[[eq:linear-threshold]] take similar values by normalizing the (\mu_V,
\sigma_V, \tau_V^N) space. The normalization factors \(
\mu_V^0=-60\mathrm{mV}, \delta \mu_V^0=10\mathrm{mV},
\sigma_V^0=4\mathrm{mV}, \delta \sigma_V^0 = 6 \mathrm{mV},
\tau_V^{N0} = 0.5, \delta \tau_V^{N0} = 1. \) arbitrarily delimits the
/fluctuation-driven/ regime (a mean value $x$ and an extent $\delta
x$, $\forall x \in \{\mu_V, \sigma_V, \tau_V^N\}$). It is kept
constant all along the study.

The fitting consisted first in a linear regression in the
phenomenological threshold space of Equation [[eq:linear-threshold]],
followed by a non-linear optimization of Equation [[eq:template]] on the
firing rate response. Both fitting were performed with the =leastsq=
method in the =optimize= package of =SciPy=.

Note that the reason for not restricting the fitting to the linear
regression is that you can not include the \(\nu_\mathrm{out}= 0 \)
points (because Erfc^{-1} has a singularity). Given the limited number
of experimental points, such a truncation would have introduced a
strong bias toward high firing response (not shown), this motivated
the introduction of the second non-linear fitting step.


** Numerical tools
<<sec:numerical-tools>>

All numerical simulations of single cell dynamics have been performed
with custom code written in the numerical library of =python=: =numpy=
and optimized with the =numba= library. For the neuronal model, each
point (a mean output frequency and its standard deviation across
trials) corresponds to numerical simulations running with a time step
dt=0.01ms, for a duration of 10s and repeated 4 times with different
seeds (one simulation duration: $\sim$ 2s of real time on a Dell
Optiplex 9020 desktop computer). Experimental protocols and
online-analysis have been written in =Elphy2=. Plots and data analysis
have been done thanks to the =SciPy= package.


** Supplementary material :noexport:
<<sec:supplementary>>

Additional analysis and information can be found at
https://github.com/yzerlaut/heterogenous_firing_response
[[citep:Zerlaut2015]]. It contains the data from all cells, the fitting
procedure as well as the numerical simulations presented in this
paper.


** Author contributions :noexport:
<<sec:author-contrib>>


*G.O. \& A.D co-supervised this work, the experimental and theoretical
part respectively. A.D. \& T.B. initially designed the project,
C.D. \& Y.Z. performed preliminary whole cell experiments,
G.O. designed the perforated patch protocols. Y.Z. designed the
dynamic-clamp protocols, performed experiments, numerical simulations
and analyzed data. Y.Z., B.T. \& A.D. discussed the results and wrote
the manuscript.


** Acknowledgments  :noexport:
<<sec:acknowledgments>>


We would like to acknowledge the contribution of Gérard Sadoc in
helping us to design the dynamic-clamp protocols. We also thank
Guillaume Hucher for the histological work as well as Manon Richard
and Aurélie Daret for animal facilities. Y.Z was supported by
fellowships from the Initiative d'Excellence Paris-Saclay and the
Fondation pour la Recherche Médicale (FDT 20150532751). Research
funded by the CNRS, the ANR (Complex-V1 project) and the European
Community (BrainScales FP7-269921 and the Human Brain Project
FP7-604102). The authors declare no competing financial interests.



* References

\bibliography{tex/biblio}

\onecolumn
\newpage
\beginsupplement


* Supplementary Information

# \vspace{5cm}

** Accuracy of the single compartment approximation
<<sec:single-comp-data>>

The single-compartment approximation is important in this study as it
is used to constrain the fluctuations of the membrane potential. We do
here a cell by cell quantification of the accuracy of the
approximation. 


\newpage
